id = "stata"
name = "Stata"
description = "Stata language support for Zed"
version = "0.5.7"
schema_version = 1
authors = ["Jonathan Marc Bearak"]
repository = "https://github.com/jbearak/zed-stata"
themes = []
icon_themes = []
languages = ["languages/stata"]
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.stata]
repository = "https://github.com/jbearak/tree-sitter-stata"
rev = "f4679d8dbd274828052b1e0c2ba1383b78853865"

[language_servers.sight]
name = "Sight"
languages = ["Stata"]
